sonar.organization=fredgod833
sonar.projectKey=fredgod833_OC10

# Modules
sonar.modules=back,front

# Backend Java
back.sonar.projectName=Backend Java
back.sonar.sources=src/main/java
back.sonar.tests=src/test/java
back.sonar.java.binaries=target/classes
back.sonar.java.libraries=target/**/*.jar
back.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Frontend Angular
front.sonar.projectName=bobapp-front
front.sonar.sources=src
front.sonar.sourceEncoding=UTF-8
front.sonar.tests=src/app
front.sonar.test.inclusions=**/*.spec.ts
front.sonar.exclusions=**/node_modules/**,**/*.spec.ts
front.sonar.typescript.lcov.reportPaths=coverage/lcov.info