name: 'CI-test'
on:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: launch front tests with coverage
        run: |
            cd front
            npm ci # install packages
            npm run test:ci
            npm run test:ci-coverage
            cd ..

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Launch maven compile with tests and coverage
        run: |
          cd back
          pwd
          mvn -B compile test

          
