name: 'CI'
on:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: launch front tests with coverage
        run: |
            cd front
            npm ci # install packages
            npm run test:ci
            npm run test:ci-coverage
            cd ..

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: launch maven compile with tests with coverage
      run: |
        cd back
        mvn -B compile
      - uses: actions/upload-artifact@v4  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-back-results
          path: ./back/target/site/jacoco
