name: 'CI-test'
on:
  [push] #pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: launch front tests with coverage
        run: |
            cd front
            npm ci # install packages
            npm run test:ci
            npm run test:ci-coverage
            cd ..

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Launch maven compile with tests and coverage
        run: |
          cd back
          pwd
          mvn -B compile test
          cd ..
          
      - name: Report Back JUnit tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Back tests results
          path: ./back/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Report Front JUnit tests
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Front tests results
          path: ./front/junit/junitReporter.xml
          reporter: java-junit
          fail-on-error: true

      - name: Upload back coverage results
        uses: actions/upload-artifact@v4
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-back-results
          path: ./back/target/site/jacoco

      - name: Upload front coverage results
        uses: actions/upload-artifact@v4
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-front-results
          path: ./front/coverage/

      

          
